
publishDir = 'docs'

title = 'Victor Touroul'

[languages]
  [languages.en]
    label = 'English'
    weight = 20
    locale = 'en-US'

  [languages.fr]
    label = 'Français'
    weight = 10
    locale = 'fr-FR'


[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20

  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'

