baseURL = 'colorivine.github.io/Portfolio2026/'

publishDir = 'docs'

theme = 'portfolio-theme'
defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = true

title = 'Victor Touroul'

[languages]
  [languages.en]
    contentDir = "content/en"
    label = 'English'
    weight = 10
    locale = 'en-US'

  [languages.fr]
    contentDir = "content/fr"
    label = 'Français'
    weight = 20
    locale = 'fr-fr'


[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20

  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'

[markup]
  [markup.goldmark.parser]
    wrapStandAloneImageWithinParagraph = false
  [markup.goldmark.parser.attribute]
    block = true

